apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hlvz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hlvz
    app.kubernetes.io/part-of: byoc-app-kbyq
  name: hlvz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: hlvz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: hlvz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ybxj-tenant/byoc-app-kbyq/hlvz@sha256:eb7a5880e6e81b08ba6f5dd6dcbc472e4a84f24d42b4f53fe93030ebb9b7977b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
